### PR TITLE
Issue 22 support for tokenisation

### PR DESCRIPTION
**Pull request by catharsisjelly**
Creating a new PR for this as I have merged it in my fork but our code is still referencing this codebase

### CODE REVIEW

**Comment by NoelLH** [comment]
@catharsisjelly I've now been given collaborator access on this repo, but I'm not really clear why this change needs to be in here too. If we're saying your fork will be maintained moving forward, it might be simpler to keep those updates in one place?

I see the changes are additive and have their own tests, which is great and the risk of BC breaks is minimal, but the main problem I foresee with merging this is that it changes the namespace of the `name` in `composer.json`. I think this is likely to cause Packagist to get upset and only accept one of the two libraries. I think some CR products might also still be referencing this version, so for any unexpected final patches they may need to be able to update the lib independently while keeping the `comicrelief` namespace.

Would it not be simpler to publish your version on Packagist under the new namespace and update your apps' references?

**Comment by catharsisjelly** [comment]
Ah, well I have actually released this on Packagist, if you want to include the tokenisation stuff in this repo too then I can remove all the other unrelated changes easily.

**Comment by NoelLH** [comment]
@catharsisjelly given the repo headline, which I can't update, has been tagged with _unmaintained_ I think it's sensible to treat this repo as abandoned now and keep major updates to your fork to avoid confusion for anyone who finds it and just looks at recent updates. I'd be happy to merge a readme update pointing new users to your repo in favour of this one.

**Comment by catharsisjelly** [comment]
I'm cool with that, I updated the README in my fork to give the team credit and such. I also plan to run that update to Omnipay 3. Killing this PR. If you want to follow my fork and continue to be involved please do so.

**Pull request closed without merging**
